#source 'https://github.com/CocoaPods/Specs.git'

target 'HaidoraRefresh', :exclusive => true do
  pod "HaidoraRefresh", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "HaidoraRefresh", :path => "../"

  
end
